coverage:
  status:
    project:
      default:
        # Don't allow total coverage to drop
        target: auto
        threshold: 0%
    patch:
      default:
        # Force new code to be at least 80% covered
        target: 80%
