ARG OTP_VERSION

FROM docker.io/library/erlang:${OTP_VERSION}

ARG THRIFT_VERSION
ARG TARGETARCH

RUN curl -L "https://github.com/valitydev/thrift/releases/download/${THRIFT_VERSION}/thrift-${THRIFT_VERSION}-linux-${TARGETARCH}.tar.gz" \
    | tar -xvz -C /usr/local/bin/

ENV CHARSET=UTF-8
ENV LANG=C.UTF-8
CMD /bin/bash
